name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v2"
      - name: Set version
        run: |
          export VERSION=${{ steps.previoustag.outputs.tag }}
      - name: Setup tools
        run: sudo apt-get install pandoc
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Install just
        uses: extractions/setup-just@v4
      - name: Build
        run: VERSION="${{ steps.previoustag.outputs.tag }}" just all

