name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup tools
        run: sudo apt-get install pandoc
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Install just
        uses: extractions/setup-just@v4
      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true
      - name: Build
        run: just build
